# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hakkinda.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_hakkinda(object):
    def setupUi(self, hakkinda):
        hakkinda.setObjectName("hakkinda")
        hakkinda.resize(525, 397)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        hakkinda.setWindowIcon(icon)
        hakkinda.setStyleSheet("\n"
"#centralwidget{border-image: url(:/arkaplan/arkaplan9.jpeg);}")
        self.centralwidget = QtWidgets.QWidget(hakkinda)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 130, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 130, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 160, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 210, 421, 151))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        hakkinda.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(hakkinda)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 525, 26))
        self.menubar.setObjectName("menubar")
        hakkinda.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(hakkinda)
        self.statusbar.setObjectName("statusbar")
        hakkinda.setStatusBar(self.statusbar)

        self.retranslateUi(hakkinda)
        QtCore.QMetaObject.connectSlotsByName(hakkinda)

    def retranslateUi(self, hakkinda):
        _translate = QtCore.QCoreApplication.translate
        hakkinda.setWindowTitle(_translate("hakkinda", "Hakkında"))
        self.label.setText(_translate("hakkinda", "Yapan:"))
        self.label_2.setText(_translate("hakkinda", "İrem ERTÜRK "))
        self.label_3.setText(_translate("hakkinda", "İnstagram:"))
        self.label_4.setText(_translate("hakkinda", "irem__erturk"))
        self.label_5.setText(_translate("hakkinda", "BOL FİLMLER DİLERİM :)"))
import anasayfa_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hakkinda = QtWidgets.QMainWindow()
    ui = Ui_hakkinda()
    ui.setupUi(hakkinda)
    hakkinda.show()
    sys.exit(app.exec_())
