# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Salonİşlemleri.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SalonIslemleri(object):
    def setupUi(self, SalonIslemleri):
        SalonIslemleri.setObjectName("SalonIslemleri")
        SalonIslemleri.resize(378, 229)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SalonIslemleri.setWindowIcon(icon)
        SalonIslemleri.setStyleSheet("#centralwidget{border-image: url(:/arkaplan/arkaplan11.jpg);}\n"
"")
        self.centralwidget = QtWidgets.QWidget(SalonIslemleri)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 10, 311, 161))
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.label_1 = QtWidgets.QLabel(self.groupBox)
        self.label_1.setGeometry(QtCore.QRect(20, 50, 61, 16))
        self.label_1.setObjectName("label_1")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_1.setGeometry(QtCore.QRect(90, 50, 171, 22))
        self.lineEdit_1.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 100, 93, 41))
        self.pushButton_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 100, 93, 41))
        self.pushButton_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        SalonIslemleri.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SalonIslemleri)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 378, 26))
        self.menubar.setObjectName("menubar")
        SalonIslemleri.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SalonIslemleri)
        self.statusbar.setObjectName("statusbar")
        SalonIslemleri.setStatusBar(self.statusbar)

        self.retranslateUi(SalonIslemleri)
        QtCore.QMetaObject.connectSlotsByName(SalonIslemleri)

    def retranslateUi(self, SalonIslemleri):
        _translate = QtCore.QCoreApplication.translate
        SalonIslemleri.setWindowTitle(_translate("SalonIslemleri", "Salon Ekle"))
        self.groupBox.setTitle(_translate("SalonIslemleri", "Salon Ekle"))
        self.label_1.setText(_translate("SalonIslemleri", "Salon Adı:"))
        self.pushButton_2.setText(_translate("SalonIslemleri", "Geri Dön"))
        self.pushButton_3.setText(_translate("SalonIslemleri", "Salon Ekle"))
import anasayfa_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SalonIslemleri = QtWidgets.QMainWindow()
    ui = Ui_SalonIslemleri()
    ui.setupUi(SalonIslemleri)
    SalonIslemleri.show()
    sys.exit(app.exec_())
