# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Satışİşlemleri.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SatisIslemleri(object):
    def setupUi(self, SatisIslemleri):
        SatisIslemleri.setObjectName("SatisIslemleri")
        SatisIslemleri.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SatisIslemleri.setWindowIcon(icon)
        SatisIslemleri.setStyleSheet("#centralwidget{border-image: url(:/arkaplan/arkaplan11.jpg);}")
        self.centralwidget = QtWidgets.QWidget(SatisIslemleri)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 500, 93, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(590, 500, 141, 22))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(730, 500, 101, 22))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 500, 341, 41))
        self.pushButton_3.setAcceptDrops(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 80, 741, 401))
        self.tableWidget.setRowCount(300)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        SatisIslemleri.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SatisIslemleri)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        SatisIslemleri.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SatisIslemleri)
        self.statusbar.setObjectName("statusbar")
        SatisIslemleri.setStatusBar(self.statusbar)

        self.retranslateUi(SatisIslemleri)
        QtCore.QMetaObject.connectSlotsByName(SatisIslemleri)

    def retranslateUi(self, SatisIslemleri):
        _translate = QtCore.QCoreApplication.translate
        SatisIslemleri.setWindowTitle(_translate("SatisIslemleri", "Satışlar"))
        self.pushButton_2.setText(_translate("SatisIslemleri", "Geri Dön"))
        self.label_3.setText(_translate("SatisIslemleri", "Toplam kazanılan tutar:"))
        self.label.setText(_translate("SatisIslemleri", "Satışlar:"))
        self.pushButton_3.setText(_translate("SatisIslemleri", "Tüm Satışları Gör"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SatisIslemleri", "Rezervasyon kodu"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SatisIslemleri", "Film adı"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("SatisIslemleri", "Salon adı"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("SatisIslemleri", "Tarih"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("SatisIslemleri", "Saat"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("SatisIslemleri", "Müşteri ad-soyad"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("SatisIslemleri", "Koltuk no"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("SatisIslemleri", "Ücret"))
import anasayfa_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SatisIslemleri = QtWidgets.QMainWindow()
    ui = Ui_SatisIslemleri()
    ui.setupUi(SatisIslemleri)
    SatisIslemleri.show()
    sys.exit(app.exec_())
